apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: svkgmpokb-go-gitops
  description: This is GitOps manifest for svkgmpokb-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=svkgmpokb-go
    backstage.io/kubernetes-id: svkgmpokb-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: svkgmpokb-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:svkgmpokb-go
